const DISTANCE_INIT = -2.0;
const DISTANCE_ERROR = -1.0;
const COORD_INIT = -200.0;
const COORD_ERROR = -300.0;

const API_KEY = "AIzaSyCr5nYLbc_koQFa6TobveKXQDxse3H1-bw";

const BLUE_COLOR_HEX = 0xFF3f4bb7;

const SCREEN_KEY = "SCREEN_KEY";
const SCREEN_START = "SCREEN_START";
const SCREEN_COORD = "SCREEN_COORD";
const SCREEN_ADDRESS = "SCREEN_ADDRESS";
const SCREEN_FINDER_ADD = "SCREEN_FINDER_ADD";
const SCREEN_FINDER_COORD = "SCREEN_FINDER_COORD";

const ADD_SCREEN_LAT = "ADD_SCREEN_LAT";
const ADD_SCREEN_LONG = "ADD_SCREEN_LONG";
const ADD_SCREEN_ADDRESS = "ADD_SCREEN_ADDRESS";
const ADD_SCREEN_DISTANCE = "ADD_SCREEN_DISTANCE";

const FINDER_SCREEN_LAT = "FINDER_SCREEN_LAT";
const FINDER_SCREEN_LONG = "FINDER_SCREEN_LONG";