name: pelengator
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  flutter_compass: ^0.4.1
  geolocator: ^5.3.2+2
  bloc: ^6.0.1
  validators: ^2.0.1
  flutter_bloc: ^6.0.1
  geodesy: ^0.3.2
  flutter_google_places: ^0.2.6
  native_state: ^1.1.1
  shared_preferences: ^0.5.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
